-- supabase/migrations/20260904000000_reel_captions.sql
--
-- ↔ خاصية "الترجمة النصية (Captions)" فى قايمة خيارات الريل
-- (components/reel/ReelOptionsSheet.tsx + components/reel/ReelCaptionsOverlay.tsx).
--
-- ⚠️ ملاحظة صريحة: العمودين دول بس تخزين نص جاهز (transcript) — التطبيق
-- مبيعملش speech-to-text ولا ترجمة تلقائية حقيقية بنفسه، لأن ده محتاج
-- تكامل مع خدمة خارجية (زي Whisper للتفريغ الصوتي + Google Translate/DeepL
-- للترجمة) مش موجودة فى المشروع دلوقتي. لحد ما بيتضاف هذا التكامل
-- (edge function تملأ العمودين دول وقت رفع الريل مثلاً)، العمودين هيفضلوا
-- فاضيين لمعظم الإعلانات، والتطبيق هيعرض بس اللي موجود فعليًا من غير ما
-- يخترع ترجمة وهمية.
alter table public.properties
  add column if not exists captions_ar text,
  add column if not exists captions_en text;

comment on column public.properties.captions_ar is
  'نص الترجمة/التفريغ الصوتي بالعربي لفيديو الريل — يتملأ يدويًا أو عبر خدمة تفريغ صوتي خارجية، مش مُنشأ تلقائيًا من التطبيق نفسه.';
comment on column public.properties.captions_en is
  'English caption/transcript text for the reel video — populated manually or via an external transcription service, not auto-generated by the app itself.';
