// ↔ الميزة الدولية لإدخال رقم الهاتف — قائمة الدول الثابتة.
//
// قرار تصميم مقصود: معملتش استيراد react-native-country-picker-modal ولا
// react-native-phone-number-input زي ما كان مقترح في المواصفة، لأن:
// 1. المواصفة نفسها طلبت "عدم تحميل مكتبة ثقيلة تؤثر على حجم التطبيق".
// 2. المكتبتين دول بيضيفوا حجم وتبعية صيانة زيادة (واحدة UI كاملة لكل
//    اختيار الدولة، والتانية UI كاملة لحقل الهاتف) لحاجة ممكن تتغطى بمكون
//    مخصص بسيط متوافق تمامًا مع تصميم التطبيق الحالي (ألوان/أحجام FormControls.tsx).
// 3. أعلام الدول هنا Unicode regional-indicator emoji مش صور — صفر أصول
//    إضافية، تشتغل native على iOS/Android من غير أي حزمة زيادة.
// المكتبة الوحيدة المُضافة فعليًا هي `libphonenumber-js` (الأخف من الاختيارات
// المقترحة في المواصفة) للتحقق والتنسيق فقط — راجع lib/phone.ts.

export type Country = {
  code: string; // ISO 3166-1 alpha-2
  callingCode: string; // بدون +
  nameAr: string;
  nameEn: string;
};

// ↔ يظهر في أعلى شاشة اختيار الدولة قبل باقي القائمة، بنفس الترتيب.
export const COMMON_COUNTRY_CODES = ["EG", "SA", "AE", "US", "GB"];

export const COUNTRIES: Country[] = [
  { code: "EG", callingCode: "20", nameAr: "مصر", nameEn: "Egypt" },
  { code: "SA", callingCode: "966", nameAr: "السعودية", nameEn: "Saudi Arabia" },
  { code: "AE", callingCode: "971", nameAr: "الإمارات", nameEn: "United Arab Emirates" },
  { code: "US", callingCode: "1", nameAr: "الولايات المتحدة", nameEn: "United States" },
  { code: "GB", callingCode: "44", nameAr: "بريطانيا", nameEn: "United Kingdom" },
  { code: "DZ", callingCode: "213", nameAr: "الجزائر", nameEn: "Algeria" },
  { code: "AD", callingCode: "376", nameAr: "أندورا", nameEn: "Andorra" },
  { code: "AO", callingCode: "244", nameAr: "أنغولا", nameEn: "Angola" },
  { code: "AG", callingCode: "1268", nameAr: "أنتيغوا وباربودا", nameEn: "Antigua and Barbuda" },
  { code: "AR", callingCode: "54", nameAr: "الأرجنتين", nameEn: "Argentina" },
  { code: "AM", callingCode: "374", nameAr: "أرمينيا", nameEn: "Armenia" },
  { code: "AU", callingCode: "61", nameAr: "أستراليا", nameEn: "Australia" },
  { code: "AT", callingCode: "43", nameAr: "النمسا", nameEn: "Austria" },
  { code: "AZ", callingCode: "994", nameAr: "أذربيجان", nameEn: "Azerbaijan" },
  { code: "BS", callingCode: "1242", nameAr: "الباهاما", nameEn: "Bahamas" },
  { code: "BH", callingCode: "973", nameAr: "البحرين", nameEn: "Bahrain" },
  { code: "BD", callingCode: "880", nameAr: "بنغلاديش", nameEn: "Bangladesh" },
  { code: "BB", callingCode: "1246", nameAr: "بربادوس", nameEn: "Barbados" },
  { code: "BY", callingCode: "375", nameAr: "بيلاروسيا", nameEn: "Belarus" },
  { code: "BE", callingCode: "32", nameAr: "بلجيكا", nameEn: "Belgium" },
  { code: "BZ", callingCode: "501", nameAr: "بليز", nameEn: "Belize" },
  { code: "BJ", callingCode: "229", nameAr: "بنين", nameEn: "Benin" },
  { code: "BT", callingCode: "975", nameAr: "بوتان", nameEn: "Bhutan" },
  { code: "BO", callingCode: "591", nameAr: "بوليفيا", nameEn: "Bolivia" },
  { code: "BA", callingCode: "387", nameAr: "البوسنة والهرسك", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", callingCode: "267", nameAr: "بوتسوانا", nameEn: "Botswana" },
  { code: "BR", callingCode: "55", nameAr: "البرازيل", nameEn: "Brazil" },
  { code: "BN", callingCode: "673", nameAr: "بروناي", nameEn: "Brunei" },
  { code: "BG", callingCode: "359", nameAr: "بلغاريا", nameEn: "Bulgaria" },
  { code: "BF", callingCode: "226", nameAr: "بوركينا فاسو", nameEn: "Burkina Faso" },
  { code: "BI", callingCode: "257", nameAr: "بوروندي", nameEn: "Burundi" },
  { code: "CV", callingCode: "238", nameAr: "الرأس الأخضر", nameEn: "Cabo Verde" },
  { code: "KH", callingCode: "855", nameAr: "كمبوديا", nameEn: "Cambodia" },
  { code: "CM", callingCode: "237", nameAr: "الكاميرون", nameEn: "Cameroon" },
  { code: "CA", callingCode: "1", nameAr: "كندا", nameEn: "Canada" },
  { code: "CF", callingCode: "236", nameAr: "أفريقيا الوسطى", nameEn: "Central African Republic" },
  { code: "TD", callingCode: "235", nameAr: "تشاد", nameEn: "Chad" },
  { code: "CL", callingCode: "56", nameAr: "تشيلي", nameEn: "Chile" },
  { code: "CN", callingCode: "86", nameAr: "الصين", nameEn: "China" },
  { code: "CO", callingCode: "57", nameAr: "كولومبيا", nameEn: "Colombia" },
  { code: "KM", callingCode: "269", nameAr: "جزر القمر", nameEn: "Comoros" },
  { code: "CG", callingCode: "242", nameAr: "الكونغو", nameEn: "Congo" },
  { code: "CD", callingCode: "243", nameAr: "الكونغو الديمقراطية", nameEn: "DR Congo" },
  { code: "CR", callingCode: "506", nameAr: "كوستاريكا", nameEn: "Costa Rica" },
  { code: "CI", callingCode: "225", nameAr: "ساحل العاج", nameEn: "Côte d'Ivoire" },
  { code: "HR", callingCode: "385", nameAr: "كرواتيا", nameEn: "Croatia" },
  { code: "CU", callingCode: "53", nameAr: "كوبا", nameEn: "Cuba" },
  { code: "CY", callingCode: "357", nameAr: "قبرص", nameEn: "Cyprus" },
  { code: "CZ", callingCode: "420", nameAr: "التشيك", nameEn: "Czechia" },
  { code: "DK", callingCode: "45", nameAr: "الدنمارك", nameEn: "Denmark" },
  { code: "DJ", callingCode: "253", nameAr: "جيبوتي", nameEn: "Djibouti" },
  { code: "DM", callingCode: "1767", nameAr: "دومينيكا", nameEn: "Dominica" },
  { code: "DO", callingCode: "1809", nameAr: "جمهورية الدومينيكان", nameEn: "Dominican Republic" },
  { code: "EC", callingCode: "593", nameAr: "الإكوادور", nameEn: "Ecuador" },
  { code: "SV", callingCode: "503", nameAr: "السلفادور", nameEn: "El Salvador" },
  { code: "GQ", callingCode: "240", nameAr: "غينيا الاستوائية", nameEn: "Equatorial Guinea" },
  { code: "ER", callingCode: "291", nameAr: "إريتريا", nameEn: "Eritrea" },
  { code: "EE", callingCode: "372", nameAr: "إستونيا", nameEn: "Estonia" },
  { code: "SZ", callingCode: "268", nameAr: "إسواتيني", nameEn: "Eswatini" },
  { code: "ET", callingCode: "251", nameAr: "إثيوبيا", nameEn: "Ethiopia" },
  { code: "FJ", callingCode: "679", nameAr: "فيجي", nameEn: "Fiji" },
  { code: "FI", callingCode: "358", nameAr: "فنلندا", nameEn: "Finland" },
  { code: "FR", callingCode: "33", nameAr: "فرنسا", nameEn: "France" },
  { code: "GA", callingCode: "241", nameAr: "الغابون", nameEn: "Gabon" },
  { code: "GM", callingCode: "220", nameAr: "غامبيا", nameEn: "Gambia" },
  { code: "GE", callingCode: "995", nameAr: "جورجيا", nameEn: "Georgia" },
  { code: "DE", callingCode: "49", nameAr: "ألمانيا", nameEn: "Germany" },
  { code: "GH", callingCode: "233", nameAr: "غانا", nameEn: "Ghana" },
  { code: "GR", callingCode: "30", nameAr: "اليونان", nameEn: "Greece" },
  { code: "GD", callingCode: "1473", nameAr: "غرينادا", nameEn: "Grenada" },
  { code: "GT", callingCode: "502", nameAr: "غواتيمالا", nameEn: "Guatemala" },
  { code: "GN", callingCode: "224", nameAr: "غينيا", nameEn: "Guinea" },
  { code: "GW", callingCode: "245", nameAr: "غينيا بيساو", nameEn: "Guinea-Bissau" },
  { code: "GY", callingCode: "592", nameAr: "غيانا", nameEn: "Guyana" },
  { code: "HT", callingCode: "509", nameAr: "هايتي", nameEn: "Haiti" },
  { code: "HN", callingCode: "504", nameAr: "هندوراس", nameEn: "Honduras" },
  { code: "HK", callingCode: "852", nameAr: "هونغ كونغ", nameEn: "Hong Kong" },
  { code: "HU", callingCode: "36", nameAr: "المجر", nameEn: "Hungary" },
  { code: "IS", callingCode: "354", nameAr: "آيسلندا", nameEn: "Iceland" },
  { code: "IN", callingCode: "91", nameAr: "الهند", nameEn: "India" },
  { code: "ID", callingCode: "62", nameAr: "إندونيسيا", nameEn: "Indonesia" },
  { code: "IR", callingCode: "98", nameAr: "إيران", nameEn: "Iran" },
  { code: "IQ", callingCode: "964", nameAr: "العراق", nameEn: "Iraq" },
  { code: "IE", callingCode: "353", nameAr: "أيرلندا", nameEn: "Ireland" },
  { code: "IL", callingCode: "972", nameAr: "إسرائيل", nameEn: "Israel" },
  { code: "IT", callingCode: "39", nameAr: "إيطاليا", nameEn: "Italy" },
  { code: "JM", callingCode: "1876", nameAr: "جامايكا", nameEn: "Jamaica" },
  { code: "JP", callingCode: "81", nameAr: "اليابان", nameEn: "Japan" },
  { code: "JO", callingCode: "962", nameAr: "الأردن", nameEn: "Jordan" },
  { code: "KZ", callingCode: "7", nameAr: "كازاخستان", nameEn: "Kazakhstan" },
  { code: "KE", callingCode: "254", nameAr: "كينيا", nameEn: "Kenya" },
  { code: "KI", callingCode: "686", nameAr: "كيريباتي", nameEn: "Kiribati" },
  { code: "KW", callingCode: "965", nameAr: "الكويت", nameEn: "Kuwait" },
  { code: "KG", callingCode: "996", nameAr: "قيرغيزستان", nameEn: "Kyrgyzstan" },
  { code: "LA", callingCode: "856", nameAr: "لاوس", nameEn: "Laos" },
  { code: "LV", callingCode: "371", nameAr: "لاتفيا", nameEn: "Latvia" },
  { code: "LB", callingCode: "961", nameAr: "لبنان", nameEn: "Lebanon" },
  { code: "LS", callingCode: "266", nameAr: "ليسوتو", nameEn: "Lesotho" },
  { code: "LR", callingCode: "231", nameAr: "ليبيريا", nameEn: "Liberia" },
  { code: "LY", callingCode: "218", nameAr: "ليبيا", nameEn: "Libya" },
  { code: "LI", callingCode: "423", nameAr: "ليختنشتاين", nameEn: "Liechtenstein" },
  { code: "LT", callingCode: "370", nameAr: "ليتوانيا", nameEn: "Lithuania" },
  { code: "LU", callingCode: "352", nameAr: "لوكسمبورغ", nameEn: "Luxembourg" },
  { code: "MO", callingCode: "853", nameAr: "ماكاو", nameEn: "Macao" },
  { code: "MG", callingCode: "261", nameAr: "مدغشقر", nameEn: "Madagascar" },
  { code: "MW", callingCode: "265", nameAr: "مالاوي", nameEn: "Malawi" },
  { code: "MY", callingCode: "60", nameAr: "ماليزيا", nameEn: "Malaysia" },
  { code: "MV", callingCode: "960", nameAr: "المالديف", nameEn: "Maldives" },
  { code: "ML", callingCode: "223", nameAr: "مالي", nameEn: "Mali" },
  { code: "MT", callingCode: "356", nameAr: "مالطا", nameEn: "Malta" },
  { code: "MH", callingCode: "692", nameAr: "جزر مارشال", nameEn: "Marshall Islands" },
  { code: "MR", callingCode: "222", nameAr: "موريتانيا", nameEn: "Mauritania" },
  { code: "MU", callingCode: "230", nameAr: "موريشيوس", nameEn: "Mauritius" },
  { code: "MX", callingCode: "52", nameAr: "المكسيك", nameEn: "Mexico" },
  { code: "FM", callingCode: "691", nameAr: "ميكرونيزيا", nameEn: "Micronesia" },
  { code: "MD", callingCode: "373", nameAr: "مولدوفا", nameEn: "Moldova" },
  { code: "MC", callingCode: "377", nameAr: "موناكو", nameEn: "Monaco" },
  { code: "MN", callingCode: "976", nameAr: "منغوليا", nameEn: "Mongolia" },
  { code: "ME", callingCode: "382", nameAr: "الجبل الأسود", nameEn: "Montenegro" },
  { code: "MA", callingCode: "212", nameAr: "المغرب", nameEn: "Morocco" },
  { code: "MZ", callingCode: "258", nameAr: "موزمبيق", nameEn: "Mozambique" },
  { code: "MM", callingCode: "95", nameAr: "ميانمار", nameEn: "Myanmar" },
  { code: "NA", callingCode: "264", nameAr: "ناميبيا", nameEn: "Namibia" },
  { code: "NR", callingCode: "674", nameAr: "ناورو", nameEn: "Nauru" },
  { code: "NP", callingCode: "977", nameAr: "نيبال", nameEn: "Nepal" },
  { code: "NL", callingCode: "31", nameAr: "هولندا", nameEn: "Netherlands" },
  { code: "NZ", callingCode: "64", nameAr: "نيوزيلندا", nameEn: "New Zealand" },
  { code: "NI", callingCode: "505", nameAr: "نيكاراغوا", nameEn: "Nicaragua" },
  { code: "NE", callingCode: "227", nameAr: "النيجر", nameEn: "Niger" },
  { code: "NG", callingCode: "234", nameAr: "نيجيريا", nameEn: "Nigeria" },
  { code: "MK", callingCode: "389", nameAr: "مقدونيا الشمالية", nameEn: "North Macedonia" },
  { code: "NO", callingCode: "47", nameAr: "النرويج", nameEn: "Norway" },
  { code: "OM", callingCode: "968", nameAr: "عُمان", nameEn: "Oman" },
  { code: "PK", callingCode: "92", nameAr: "باكستان", nameEn: "Pakistan" },
  { code: "PW", callingCode: "680", nameAr: "بالاو", nameEn: "Palau" },
  { code: "PS", callingCode: "970", nameAr: "فلسطين", nameEn: "Palestine" },
  { code: "PA", callingCode: "507", nameAr: "بنما", nameEn: "Panama" },
  { code: "PG", callingCode: "675", nameAr: "بابوا غينيا الجديدة", nameEn: "Papua New Guinea" },
  { code: "PY", callingCode: "595", nameAr: "باراغواي", nameEn: "Paraguay" },
  { code: "PE", callingCode: "51", nameAr: "بيرو", nameEn: "Peru" },
  { code: "PH", callingCode: "63", nameAr: "الفلبين", nameEn: "Philippines" },
  { code: "PL", callingCode: "48", nameAr: "بولندا", nameEn: "Poland" },
  { code: "PT", callingCode: "351", nameAr: "البرتغال", nameEn: "Portugal" },
  { code: "QA", callingCode: "974", nameAr: "قطر", nameEn: "Qatar" },
  { code: "RO", callingCode: "40", nameAr: "رومانيا", nameEn: "Romania" },
  { code: "RU", callingCode: "7", nameAr: "روسيا", nameEn: "Russia" },
  { code: "RW", callingCode: "250", nameAr: "رواندا", nameEn: "Rwanda" },
  { code: "KN", callingCode: "1869", nameAr: "سانت كيتس ونيفيس", nameEn: "Saint Kitts and Nevis" },
  { code: "LC", callingCode: "1758", nameAr: "سانت لوسيا", nameEn: "Saint Lucia" },
  { code: "VC", callingCode: "1784", nameAr: "سانت فينسنت والغرينادين", nameEn: "Saint Vincent and the Grenadines" },
  { code: "WS", callingCode: "685", nameAr: "ساموا", nameEn: "Samoa" },
  { code: "SM", callingCode: "378", nameAr: "سان مارينو", nameEn: "San Marino" },
  { code: "ST", callingCode: "239", nameAr: "ساو تومي وبرينسيب", nameEn: "Sao Tome and Principe" },
  { code: "SN", callingCode: "221", nameAr: "السنغال", nameEn: "Senegal" },
  { code: "RS", callingCode: "381", nameAr: "صربيا", nameEn: "Serbia" },
  { code: "SC", callingCode: "248", nameAr: "سيشل", nameEn: "Seychelles" },
  { code: "SL", callingCode: "232", nameAr: "سيراليون", nameEn: "Sierra Leone" },
  { code: "SG", callingCode: "65", nameAr: "سنغافورة", nameEn: "Singapore" },
  { code: "SK", callingCode: "421", nameAr: "سلوفاكيا", nameEn: "Slovakia" },
  { code: "SI", callingCode: "386", nameAr: "سلوفينيا", nameEn: "Slovenia" },
  { code: "SB", callingCode: "677", nameAr: "جزر سليمان", nameEn: "Solomon Islands" },
  { code: "SO", callingCode: "252", nameAr: "الصومال", nameEn: "Somalia" },
  { code: "ZA", callingCode: "27", nameAr: "جنوب أفريقيا", nameEn: "South Africa" },
  { code: "KR", callingCode: "82", nameAr: "كوريا الجنوبية", nameEn: "South Korea" },
  { code: "SS", callingCode: "211", nameAr: "جنوب السودان", nameEn: "South Sudan" },
  { code: "ES", callingCode: "34", nameAr: "إسبانيا", nameEn: "Spain" },
  { code: "LK", callingCode: "94", nameAr: "سريلانكا", nameEn: "Sri Lanka" },
  { code: "SD", callingCode: "249", nameAr: "السودان", nameEn: "Sudan" },
  { code: "SR", callingCode: "597", nameAr: "سورينام", nameEn: "Suriname" },
  { code: "SE", callingCode: "46", nameAr: "السويد", nameEn: "Sweden" },
  { code: "CH", callingCode: "41", nameAr: "سويسرا", nameEn: "Switzerland" },
  { code: "SY", callingCode: "963", nameAr: "سوريا", nameEn: "Syria" },
  { code: "TW", callingCode: "886", nameAr: "تايوان", nameEn: "Taiwan" },
  { code: "TJ", callingCode: "992", nameAr: "طاجيكستان", nameEn: "Tajikistan" },
  { code: "TZ", callingCode: "255", nameAr: "تنزانيا", nameEn: "Tanzania" },
  { code: "TH", callingCode: "66", nameAr: "تايلاند", nameEn: "Thailand" },
  { code: "TL", callingCode: "670", nameAr: "تيمور الشرقية", nameEn: "Timor-Leste" },
  { code: "TG", callingCode: "228", nameAr: "توغو", nameEn: "Togo" },
  { code: "TO", callingCode: "676", nameAr: "تونغا", nameEn: "Tonga" },
  { code: "TT", callingCode: "1868", nameAr: "ترينيداد وتوباغو", nameEn: "Trinidad and Tobago" },
  { code: "TN", callingCode: "216", nameAr: "تونس", nameEn: "Tunisia" },
  { code: "TR", callingCode: "90", nameAr: "تركيا", nameEn: "Turkey" },
  { code: "TM", callingCode: "993", nameAr: "تركمانستان", nameEn: "Turkmenistan" },
  { code: "TV", callingCode: "688", nameAr: "توفالو", nameEn: "Tuvalu" },
  { code: "UG", callingCode: "256", nameAr: "أوغندا", nameEn: "Uganda" },
  { code: "UA", callingCode: "380", nameAr: "أوكرانيا", nameEn: "Ukraine" },
  { code: "UY", callingCode: "598", nameAr: "أوروغواي", nameEn: "Uruguay" },
  { code: "UZ", callingCode: "998", nameAr: "أوزبكستان", nameEn: "Uzbekistan" },
  { code: "VU", callingCode: "678", nameAr: "فانواتو", nameEn: "Vanuatu" },
  { code: "VA", callingCode: "379", nameAr: "الفاتيكان", nameEn: "Vatican City" },
  { code: "VE", callingCode: "58", nameAr: "فنزويلا", nameEn: "Venezuela" },
  { code: "VN", callingCode: "84", nameAr: "فيتنام", nameEn: "Vietnam" },
  { code: "YE", callingCode: "967", nameAr: "اليمن", nameEn: "Yemen" },
  { code: "ZM", callingCode: "260", nameAr: "زامبيا", nameEn: "Zambia" },
  { code: "ZW", callingCode: "263", nameAr: "زيمبابوي", nameEn: "Zimbabwe" },
];

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

export function findCountry(iso2: string | null | undefined): Country | undefined {
  if (!iso2) return undefined;
  return COUNTRY_BY_CODE.get(iso2.toUpperCase());
}

// ↔ يحوّل كود الدولة (EG, SA, ...) لعلم Unicode مباشرة — كل حرف من الكود
// بيتحول لـ "Regional Indicator Symbol" المقابل له (إزاحة ثابتة 127397 عن
// كود الحرف اللاتيني)، فمثلاً "EG" → 🇪🇬. الطريقة دي معمول بيها في كل
// المتصفحات وأنظمة التشغيل الحديثة تقريبًا (iOS/Android/Web) بدون أي صور.
export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(char.charCodeAt(0) + 127397));
}
